version: 2.1

orbs:
    node: circleci/node@4.1.0

jobs:
    build:
        docker:
            - image: circleci/openjdk:stretch
        steps:
            - checkout
            - run:
                name: Giving permission
                command: chmod +x test.sh
            - run:
                command: ./test.sh
